### ISSUE TITLE
Multiple language in panel support is missing for texts

### ISSUE THREAD

**Issue by jonabaptistella** [distantnative/field-switch#9]
Hi,

The plugin is works great, but I really hope that you can add support to the case under:

```
  slidershow:
    label:
      nb: Sku av og på slideshow
      en: On/Off slideshow
    type: switch
    texts:
      nb: - Av
            - På
      en: - Slideshow is on
            - Slideshow is off
```

**Comment by distantnative** [comment]
Sorry for the late reply, I had to check it out myself to realize that it is already supported, you just mixed up the syntax:

```
  slidershow:
    label:
      nb: Sku av og på slideshow
      en: On/Off slideshow
    type: switch
    texts:
      -
        en: Slideshow is on
        nb: Av
      -
        en: Slideshow is off
        nb: På
```

Will add an example to the README though. Thanks for pointing to the confusion! :)
